### ISSUE TITLE
Update during onboarding fails when trying to reach raspbian.raspberrypi.org

### ISSUE THREAD

**Issue by olivierwilkinson** [pi-top/pt-web-portal#30]
<img width="848" alt="Screenshot 2021-05-12 at 17 29 35" src="https://user-images.githubusercontent.com/15321261/118011718-487b7600-b348-11eb-90d3-9511eb4c6f74.png">

## Steps to Reproduce:

- Download OS from pi-top.com
- Flash SD card with OS
- Go through onboarding via VNC
- Connect to WiFi during onboarding
- Update should fail.

**Comment by m-roberts** [comment]
Upgrade failure is sadly just network related. UX issue has been addressed in a separate Issue and merged in. Miniscreen issue has been moved into [here](https://github.com/pi-top/pt-web-portal/issues/72#issuecomment-872322722) (until it has a proper home).
