### ISSUE TITLE
Upgrade page error message overflows container

### ISSUE THREAD

**Issue by olivierwilkinson** [pi-top/pt-web-portal#31]
The error message should have `overflow: hidden` so it does not overlap with buttons and red warning message.

<img width="848" alt="Screenshot 2021-05-12 at 17 29 35" src="https://user-images.githubusercontent.com/15321261/118012070-96907980-b348-11eb-8d3a-d1dfcb1e6828.png">

**Comment by m-roberts** [comment]
Fixed!
